export const PokemonActionTypes = {
    ADD_NEW_POKEMON: 'ADD_NEW_POKEMON',
    SELECT_POKEMON: 'SELECT_POKEMON',
    FETCH_POKEMON_DATA_START: 'FETCH_POKEMON_DATA_START',
    FETCH_POKEMON_DATA_SUCCESS: 'FETCH_POKEMON_DATA_SUCCESS',
    FETCH_POKEMON_DATA_FAILURE: 'FETCH_POKEMON_DATA_FAILURE',
    ADD_POKEMON_TO_SELECTED: 'ADD_POKEMON_TO_SELECTED'
}